apiVersion: apps/v1
kind: Deployment
metadata:
  name: beer-catalog-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beer-catalog
  template:
    metadata:
      labels:
        app: beer-catalog
    spec:
      containers:
      - name: beer-catalog-container
        image: ulaj/beer-catalog-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
