apiVersion: v1
kind: Service
metadata:
  name: beer-catalog-service
spec:
  selector:
    app: beer-catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000  # Belirlediğiniz NodePort
  type: NodePort